# Generated by Django 4.1.5 on 2023-01-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="published",
            field=models.CharField(
                choices=[("active", "На сайте"), ("inactive", "В архиве")],
                default="inactive",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
